### ISSUE TITLE
Missing CDK Bootstrap Guidance

### ISSUE THREAD

**Issue by nibrahv** [aws-samples/rag-with-amazon-bedrock-and-pgvector#3]
Unable to run the initial "npx cdk deploy BaseInfraStack" step due to environment not having been bootstrapped.  

![image](https://github.com/aws-samples/rag-with-amazon-bedrock-and-pgvector/assets/10162226/ee61f677-f97c-4634-9b1a-ec9fb2b31723)

Performing "npx cdk bootstrap" resolved the issue and allowed me to proceed.

**Comment by tanveerg** [comment]
@nibrahv thanks for letting me know. 

I have added it now - https://github.com/aws-samples/rag-with-amazon-bedrock-and-pgvector/commit/99e3c52dafaf81accc07de38cb992bbf09736cfd

Will close the issue out.

**Comment by nibrahv** [comment]
You are awesome, thank you!
