### ISSUE TITLE
Typo in Create a self-signed SSL certificate section

### ISSUE THREAD

**Issue by nibrahv** [aws-samples/rag-with-amazon-bedrock-and-pgvector#4]
Typo in Create a self-signed SSL certificate section:

Currently:
python api-key-secret-manager-upload.py.py -s openAiApiKey

Should be:
python api-key-secret-manager-upload.py -s openAiApiKey

**Comment by tanveerg** [comment]
Thanks again , it is fixed - https://github.com/aws-samples/rag-with-amazon-bedrock-and-pgvector/commit/91c354c887866463293e825111aa86eb80553cd1
